// scripts/blog-agent/publish.ts
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'fs';
import { execSync } from 'child_process';
import { join } from 'path';
import { tmpdir } from 'os';
import type { BlogDraft } from './types';

const BLOG_DATA_PATH = 'lib/blog-data.ts';

export function getExistingSlugs(fileContent: string): string[] {
  const slugRegex = /slug:\s*['"]([^'"]+)['"]/g;
  const slugs: string[] = [];
  let match;
  while ((match = slugRegex.exec(fileContent)) !== null) {
    slugs.push(match[1]);
  }
  return slugs;
}

export function formatBlogPostEntry(draft: BlogDraft): string {
  const escapedContent = draft.content.replace(/`/g, '\\`').replace(/\$/g, '\\$');
  const escapedExcerpt = draft.excerpt.replace(/'/g, "\\'");
  const escapedTitle = draft.title.replace(/'/g, "\\'");

  return `  {
    title: '${escapedTitle}',
    slug: '${draft.slug}',
    excerpt:
      '${escapedExcerpt}',
    date: '${draft.date}',
    author: '${draft.author}',
    tags: [${draft.tags.map((t) => `'${t}'`).join(', ')}],
    readingTime: ${draft.readingTime},
    content: \`
${escapedContent}
\`,
  }`;
}

function exec(cmd: string): string {
  return execSync(cmd, { encoding: 'utf-8' }).trim();
}

export async function publishDraft(draft: BlogDraft): Promise<{ prUrl: string; branch: string } | null> {
  try {
    const blogDataContent = readFileSync(BLOG_DATA_PATH, 'utf-8');

    // Check for duplicate slug
    const existingSlugs = getExistingSlugs(blogDataContent);
    if (existingSlugs.includes(draft.slug)) {
      console.log(JSON.stringify({
        level: 'warn',
        message: 'Blog post with this slug already exists',
        slug: draft.slug,
      }));
      return null;
    }

    // Create branch with unique suffix if branch already exists
    const baseBranch = `blog/${draft.date}-${draft.slug}`;
    exec('git checkout main');
    exec('git pull origin main');

    let branchName = baseBranch;
    try {
      exec(`git checkout -b ${branchName}`);
    } catch {
      // Branch exists locally or remotely — add numeric suffix
      const suffix = Math.floor(Math.random() * 1000);
      branchName = `${baseBranch}-${suffix}`;
      exec(`git checkout -b ${branchName}`);
    }

    // Insert new post at the beginning of the array
    const newEntry = formatBlogPostEntry(draft);
    const updatedContent = blogDataContent.replace(
      'export const blogPosts: BlogPost[] = [',
      `export const blogPosts: BlogPost[] = [\n${newEntry},`
    );
    writeFileSync(BLOG_DATA_PATH, updatedContent);

    // Commit and push
    exec(`git add ${BLOG_DATA_PATH}`);
    exec(`git commit -m "feat(blog): add post \\"${draft.title}\\""`);
    exec(`git push origin ${branchName}`);

    // Create PR using --body-file to avoid shell escaping issues
    const prBody = `## New Blog Post: ${draft.title}

**Excerpt:** ${draft.excerpt}

**Tags:** ${draft.tags.join(', ')}
**Reading Time:** ${draft.readingTime} min
**Format:** Auto-generated from social media pain points

---
*Generated by the SEO Blog Agent*`;

    const tmpDir = mkdtempSync(join(tmpdir(), 'blog-agent-'));
    const bodyFile = join(tmpDir, 'pr-body.md');
    writeFileSync(bodyFile, prBody);

    let prUrl: string;
    try {
      prUrl = exec(
        `gh pr create --title "Blog: ${draft.title.replace(/"/g, '\\"')}" --body-file "${bodyFile}" --base main --head ${branchName} --assignee alittlenerdy`
      );
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }

    console.log(JSON.stringify({
      level: 'info',
      message: 'Blog post PR created',
      prUrl,
      branch: branchName,
      slug: draft.slug,
    }));

    return { prUrl, branch: branchName };
  } catch (error) {
    console.log(JSON.stringify({
      level: 'error',
      message: 'Failed to publish blog draft',
      error: error instanceof Error ? error.message : String(error),
    }));
    return null;
  }
}
