/**
 * MAP Export — Markdown and JSON output
 *
 * Converts a stored MAP into shareable formats:
 * - Structured JSON (API consumers)
 * - Markdown (copy-paste, email, docs)
 * - Plain text (clipboard)
 */

import { getMapWithSteps } from '@/lib/map/store';
import type { MutualActionPlan, MapStep } from '@/lib/db/schema';

// ── Types ────────────────────────────────────────────────────────────

export interface MapExport {
  json: MapJsonExport;
  markdown: string;
  plainText: string;
}

export interface MapJsonExport {
  id: string;
  title: string;
  summary: string;
  status: string;
  meetingId: string;
  dealContextId: string | null;
  createdAt: string;
  steps: MapStepJsonExport[];
}

export interface MapStepJsonExport {
  order: number;
  title: string;
  description: string | null;
  owner: string | null;
  status: string;
  dueDate: string | null;
  sourceType: string | null;
}

// ── Export Functions ──────────────────────────────────────────────────

/**
 * Export a MAP in all formats by ID.
 */
export async function exportMap(mapId: string): Promise<MapExport | null> {
  const map = await getMapWithSteps(mapId);
  if (!map) return null;

  return {
    json: toJson(map, map.steps),
    markdown: toMarkdown(map, map.steps),
    plainText: toPlainText(map, map.steps),
  };
}

/**
 * Export a MAP as structured JSON.
 */
export function toJson(map: MutualActionPlan, steps: MapStep[]): MapJsonExport {
  return {
    id: map.id,
    title: map.title,
    summary: map.summary,
    status: map.status,
    meetingId: map.meetingId,
    dealContextId: map.dealContextId,
    createdAt: map.createdAt.toISOString(),
    steps: steps.map((s) => ({
      order: s.sortOrder,
      title: s.title,
      description: s.description,
      owner: s.owner,
      status: s.status,
      dueDate: s.dueDate,
      sourceType: s.sourceType,
    })),
  };
}

/**
 * Export a MAP as markdown.
 */
export function toMarkdown(map: MutualActionPlan, steps: MapStep[]): string {
  const lines: string[] = [
    `# ${map.title}`,
    '',
    map.summary,
    '',
    `**Status:** ${map.status} | **Created:** ${map.createdAt.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    '',
    '---',
    '',
    '## Action Items',
    '',
  ];

  for (const step of steps) {
    const checkbox = step.status === 'completed' ? '[x]' : '[ ]';
    const ownerTag = step.owner ? ` — *${step.owner}*` : '';
    const dueTag = step.dueDate ? ` (${step.dueDate})` : '';
    const sourceTag = step.sourceType ? ` \`${step.sourceType}\`` : '';

    lines.push(`- ${checkbox} **${step.title}**${ownerTag}${dueTag}${sourceTag}`);

    if (step.description) {
      lines.push(`  ${step.description}`);
    }
  }

  lines.push('', '---', '', '*Generated by ReplySequence AI*');

  return lines.join('\n');
}

/**
 * Export a MAP as plain text (clipboard-friendly).
 */
export function toPlainText(map: MutualActionPlan, steps: MapStep[]): string {
  const lines: string[] = [
    map.title.toUpperCase(),
    '='.repeat(map.title.length),
    '',
    map.summary,
    '',
  ];

  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];
    const status = step.status === 'completed' ? '✓' : '○';
    const owner = step.owner ? ` [${step.owner}]` : '';
    const due = step.dueDate ? ` — ${step.dueDate}` : '';

    lines.push(`${status} ${i + 1}. ${step.title}${owner}${due}`);

    if (step.description) {
      lines.push(`   ${step.description}`);
    }
  }

  return lines.join('\n');
}
